import { type ReactNode } from "react";
import { Copy, Download, FileText, FolderOpen, type LucideIcon } from "lucide-react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export type ArtifactPreviewProps = {
  /** Artifact title, e.g. "generated-report.pdf". */
  title: string;
  /** Artifact type shown as a small label, e.g. "PDF · 24 KB". */
  meta?: string;
  /** Icon for the artifact type (defaults to FileText). */
  icon?: LucideIcon;
  /** Rendered content (e.g. an image, a diff, a preview card). */
  children?: ReactNode;
  /** Called by the Copy action button. */
  onCopy?: () => void;
  /** Called by the Open action button. */
  onOpen?: () => void;
  /** Called by the Download action button. */
  onDownload?: () => void;
  className?: string;
};

/**
 * Preview card for an artifact generated by the agent (file, report, diff…):
 * type icon + title + meta header, content slot, and optional actions.
 * Actions only render when their callback is provided. Presentational.
 */
export function ArtifactPreview({
  title,
  meta,
  icon: Icon = FileText,
  children,
  onCopy,
  onOpen,
  onDownload,
  className,
}: ArtifactPreviewProps) {
  const hasActions = onCopy !== undefined || onOpen !== undefined || onDownload !== undefined;

  return (
    <div
      data-artifact-preview
      className={cn("overflow-hidden rounded-xl border bg-card text-card-foreground", className)}
    >
      <div className="flex items-center gap-2 border-b px-3 py-2">
        <div className="flex size-7 shrink-0 items-center justify-center rounded-md bg-muted">
          <Icon aria-hidden className="size-4 text-muted-foreground" />
        </div>
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium">{title}</p>
          {meta && <p className="truncate text-xs text-muted-foreground">{meta}</p>}
        </div>
        {hasActions && (
          <div className="flex shrink-0 items-center gap-1">
            {onCopy !== undefined && (
              <Button
                type="button"
                variant="ghost"
                size="icon-sm"
                aria-label={`Copy ${title}`}
                onClick={onCopy}
              >
                <Copy aria-hidden />
              </Button>
            )}
            {onOpen !== undefined && (
              <Button
                type="button"
                variant="ghost"
                size="icon-sm"
                aria-label={`Open ${title}`}
                onClick={onOpen}
              >
                <FolderOpen aria-hidden />
              </Button>
            )}
            {onDownload !== undefined && (
              <Button
                type="button"
                variant="ghost"
                size="icon-sm"
                aria-label={`Download ${title}`}
                onClick={onDownload}
              >
                <Download aria-hidden />
              </Button>
            )}
          </div>
        )}
      </div>
      {children && <div className="px-3 py-2">{children}</div>}
    </div>
  );
}
